# ===============================
# APPLICATION CONFIGURATION
# ===============================
spring.application.name=StayNest


# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
server.servlet.context-path=/api/v1


# ===============================
# DATABASE CONFIGURATION (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/staynestdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================                                                   
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Format SQL logs nicely
spring.jpa.properties.hibernate.format_sql=true

# Recommended dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=FGD/^uePqi0eGbCQ9umZsKziX2/v84BdoksiYVcrtn0=
jwt.expiration-ms=3600000
jwt.issuer=StayNest


# ===============================
# JACKSON (JSON) CONFIGURATION
# ===============================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata


# ===============================
# CONNECTION POOL CONFIGURATION (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000


# ===============================
# LOGGING CONFIGURATION
# ===============================

# Spring Web logs
logging.level.org.springframework.web=DEBUG

# Hibernate SQL queries
logging.level.org.hibernate.SQL=DEBUG

# Show SQL parameter values (use TRACE only in dev)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Project-specific logging
logging.level.com.staynest=DEBUG
